// Package certs manages the controller's internal PKI: a self-signed CA,
// the server's TLS certificate, and per-agent client certificates. mTLS is
// the only authentication mechanism — an agent's certificate CN is its
// client name.
package certs

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// CA is the wgmgt certificate authority.
type CA struct {
	Cert *x509.Certificate
	Key  *ecdsa.PrivateKey
}

// NewCA generates a fresh CA (10-year validity).
func NewCA() (*CA, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, err
	}
	tmpl := &x509.Certificate{
		SerialNumber:          randomSerial(),
		Subject:               pkix.Name{CommonName: "wgmgt-ca"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(10, 0, 0),
		IsCA:                  true,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, err
	}
	return &CA{Cert: cert, Key: key}, nil
}

// LoadCA reads ca.pem/ca.key from dir.
func LoadCA(dir string) (*CA, error) {
	certPEM, err := os.ReadFile(filepath.Join(dir, "ca.pem"))
	if err != nil {
		return nil, err
	}
	keyPEM, err := os.ReadFile(filepath.Join(dir, "ca.key"))
	if err != nil {
		return nil, err
	}
	return parseCA(certPEM, keyPEM)
}

// Save writes ca.pem/ca.key into dir (0600).
func (ca *CA) Save(dir string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "ca.pem"), pemCert(ca.Cert, "CERTIFICATE"), 0o644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "ca.key"), pemKey(ca.Key), 0o600)
}

// LoadOrNewCA returns the CA in dir, creating it on first run. A ca.pem
// without its key is a hard error, not a first run: silently regenerating
// would invalidate every issued agent certificate (split brain).
func LoadOrNewCA(dir string) (*CA, error) {
	ca, err := LoadCA(dir)
	if err == nil {
		return ca, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	if _, statErr := os.Stat(filepath.Join(dir, "ca.pem")); statErr == nil {
		return nil, fmt.Errorf("ca.pem exists but its key is unreadable (%v) — refusing to regenerate the CA, which would invalidate all agent certificates; restore ca.key or move the whole PKI directory away", err)
	}
	ca, err = NewCA()
	if err != nil {
		return nil, err
	}
	return ca, ca.Save(dir)
}

// NewServerCert issues the controller's TLS certificate with the given
// hosts as DNS/IP SANs plus localhost.
func (ca *CA) NewServerCert(hosts []string) (certPEM, keyPEM []byte, err error) {
	return ca.issue("wgmgt-server", hosts, x509.ExtKeyUsageServerAuth)
}

// NewAgentCert issues a client certificate; CN is the client name.
func (ca *CA) NewAgentCert(name string) (certPEM, keyPEM []byte, err error) {
	return ca.issue(name, nil, x509.ExtKeyUsageClientAuth)
}

// NewAgentCertFromKey issues a client certificate (CN=name, EKU ClientAuth)
// for a PEM "PUBLIC KEY" (PKIX) generated by the agent itself — the private
// key never leaves the enrolling client. Only ECDSA P-256 keys are accepted.
func (ca *CA) NewAgentCertFromKey(name string, pubPEM []byte) ([]byte, error) {
	block, _ := pem.Decode(pubPEM)
	if block == nil || block.Type != "PUBLIC KEY" {
		return nil, errors.New("public key: no PEM PUBLIC KEY block")
	}
	pub, err := x509.ParsePKIXPublicKey(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("public key: %v", err)
	}
	ecPub, ok := pub.(*ecdsa.PublicKey)
	if !ok || ecPub.Curve != elliptic.P256() {
		return nil, errors.New("public key: only ECDSA P-256 keys are accepted")
	}
	return ca.issueForKey(name, nil, x509.ExtKeyUsageClientAuth, ecPub)
}

// CAFingerprint returns the hex SHA-256 fingerprint of the CA certificate
// DER — the value agents pin via --ca-hash during bootstrap enrollment.
func (ca *CA) CAFingerprint() string {
	sum := sha256.Sum256(ca.Cert.Raw)
	return fmt.Sprintf("%x", sum)
}

// CAPEM returns the CA certificate in PEM form.
func (ca *CA) CAPEM() []byte {
	return pemCert(ca.Cert, "CERTIFICATE")
}

func (ca *CA) issue(cn string, hosts []string, eku x509.ExtKeyUsage) (certPEM, keyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	certPEM, err = ca.issueForKey(cn, hosts, eku, &key.PublicKey)
	if err != nil {
		return nil, nil, err
	}
	return certPEM, pemKey(key), nil
}

func (ca *CA) issueForKey(cn string, hosts []string, eku x509.ExtKeyUsage, pub crypto.PublicKey) ([]byte, error) {
	tmpl := &x509.Certificate{
		SerialNumber: randomSerial(),
		Subject:      pkix.Name{CommonName: cn},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().AddDate(5, 0, 0),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{eku},
	}
	for _, h := range hosts {
		if ip := net.ParseIP(h); ip != nil {
			tmpl.IPAddresses = append(tmpl.IPAddresses, ip)
		} else {
			tmpl.DNSNames = append(tmpl.DNSNames, h)
		}
	}
	if eku == x509.ExtKeyUsageServerAuth {
		tmpl.DNSNames = append(tmpl.DNSNames, "localhost")
		tmpl.IPAddresses = append(tmpl.IPAddresses, net.ParseIP("127.0.0.1"), net.ParseIP("::1"))
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, ca.Cert, pub, ca.Key)
	if err != nil {
		return nil, err
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, err
	}
	return pemCert(cert, "CERTIFICATE"), nil
}

// Fingerprint returns the hex SHA-256 fingerprint of a PEM certificate.
func Fingerprint(certPEM []byte) (string, error) {
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return "", errors.New("no PEM block")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(cert.Raw)
	return fmt.Sprintf("%x", sum), nil
}

// EnsureServerCerts makes sure dir contains ca.pem/ca.key and
// server.pem/server.key valid for hosts, creating what is missing.
// Returns the TLS server certificate.
func EnsureServerCerts(dir string, hosts []string) (tls.Certificate, *x509.CertPool, error) {
	ca, err := LoadOrNewCA(dir)
	if err != nil {
		return tls.Certificate{}, nil, err
	}
	certPath := filepath.Join(dir, "server.pem")
	keyPath := filepath.Join(dir, "server.key")
	cert, err := tls.LoadX509KeyPair(certPath, keyPath)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return tls.Certificate{}, nil, err
		}
		certPEM, keyPEM, err := ca.NewServerCert(hosts)
		if err != nil {
			return tls.Certificate{}, nil, err
		}
		if err := os.WriteFile(certPath, certPEM, 0o644); err != nil {
			return tls.Certificate{}, nil, err
		}
		if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
			return tls.Certificate{}, nil, err
		}
		cert, err = tls.X509KeyPair(certPEM, keyPEM)
		if err != nil {
			return tls.Certificate{}, nil, err
		}
	}
	pool := x509.NewCertPool()
	pool.AddCert(ca.Cert)
	return cert, pool, nil
}

// IssueServerCert is the interactive setup path (wgmgt init): it ensures
// the CA in dir and issues the server certificate covering the given DNS
// names and IP addresses (localhost is always included on top). An
// existing certificate whose SANs already cover the request is reused
// as-is; otherwise a fresh one is written. Returns whether the existing
// certificate was kept. The server startup path is EnsureServerCerts,
// which only fills in what is missing.
func IssueServerCert(dir string, dnsNames, ips []string) (kept bool, err error) {
	ca, err := LoadOrNewCA(dir)
	if err != nil {
		return false, err
	}
	certPath := filepath.Join(dir, "server.pem")
	keyPath := filepath.Join(dir, "server.key")
	if cert, err := tls.LoadX509KeyPair(certPath, keyPath); err == nil {
		if leaf, err := x509.ParseCertificate(cert.Certificate[0]); err == nil && sanCovers(leaf, dnsNames, ips) {
			return true, nil
		}
	}
	hosts := make([]string, 0, len(dnsNames)+len(ips))
	for _, d := range dnsNames {
		if d = strings.TrimSpace(d); d != "" {
			hosts = append(hosts, d)
		}
	}
	for _, s := range ips {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if net.ParseIP(s) == nil {
			return false, fmt.Errorf("invalid SAN IP %q", s)
		}
		hosts = append(hosts, s)
	}
	certPEM, keyPEM, err := ca.NewServerCert(hosts)
	if err != nil {
		return false, err
	}
	if err := os.WriteFile(certPath, certPEM, 0o644); err != nil {
		return false, err
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		return false, err
	}
	return false, nil
}

// sanCovers reports whether leaf's SANs already include every requested
// DNS name and IP; the always-added localhost entries need no check.
func sanCovers(leaf *x509.Certificate, dnsNames, ips []string) bool {
	haveDNS := make(map[string]bool, len(leaf.DNSNames))
	for _, d := range leaf.DNSNames {
		haveDNS[strings.ToLower(d)] = true
	}
	for _, d := range dnsNames {
		if d = strings.TrimSpace(d); d != "" && !haveDNS[strings.ToLower(d)] {
			return false
		}
	}
	haveIP := make(map[string]bool, len(leaf.IPAddresses))
	for _, ip := range leaf.IPAddresses {
		haveIP[ip.String()] = true
	}
	for _, s := range ips {
		if s = strings.TrimSpace(s); s != "" && !haveIP[s] {
			return false
		}
	}
	return true
}

// --- helpers ---

func randomSerial() *big.Int {
	limit := new(big.Int).Lsh(big.NewInt(1), 120)
	n, err := rand.Int(rand.Reader, limit)
	if err != nil {
		return big.NewInt(1)
	}
	return n
}

func pemCert(cert *x509.Certificate, typ string) []byte {
	return pem.EncodeToMemory(&pem.Block{Type: typ, Bytes: cert.Raw})
}

func pemKey(key *ecdsa.PrivateKey) []byte {
	der, _ := x509.MarshalECPrivateKey(key)
	return pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: der})
}

func parseCA(certPEM, keyPEM []byte) (*CA, error) {
	block, _ := pem.Decode(certPEM)
	if block == nil {
		return nil, errors.New("ca.pem: no PEM block")
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, err
	}
	kb, _ := pem.Decode(keyPEM)
	if kb == nil {
		return nil, errors.New("ca.key: no PEM block")
	}
	key, err := x509.ParseECPrivateKey(kb.Bytes)
	if err != nil {
		return nil, err
	}
	return &CA{Cert: cert, Key: key}, nil
}
